### ISSUE TITLE
I am no longer able to access the Start Menu in Training Mode

### ISSUE THREAD

**Issue by wanderrful** [dantarion/SF5DInput#6]
Installed the most recent .dll files as instructed because this was recommended to me by a friend when I told them about how my joystick doesn't work in SF5 without Joy2Key.

I can no longer use the keyboard at all to access the Start Menu when in Training Mode.  Even when I remove the .dll files and unplug the keyboard.

The popular consensus of the people in the /r/StreetFighter Discord server is that the game has interpreted your .dll files as an attempt to hack the game.

edit: this also apparently affects everything where you're not in the main menu, such as challenge trials, story mode, or training

**Comment by dantarion** [comment]
Uh...no offense but...you would think that if there was any kind of anti-hacking code in the game, I of all people would have run into it by now.

You are the first to report this bug, and the only person claiming that their game has been affected by the dll's even after they have been removed.

There is is no way to remap the keyboard buttons, and there are no persistant changes made to any config files or settings. Can you please be very certain that this problem was actually caused by this project?

We can't reproduce it or fix it based on your report, and it doesn't match up with my understanding of how the DLL works or how SF5 works. I obviously would be very alarmed if there was some edge case in this software that permanently breaks keyboard inputs, but I don't understand how this could happen.

**Comment by wanderrful** [comment]
I'm just as confused as you are!  I was practicing anti-airs in training mode, I saw a friend recommend this, I installed it into the proper folder, I found that it detected some buttons but not all, I closed the game and deleted it because I couldn't see how to map the buttons, then I started the game again as normal and now I have this issue.

Even removing the joystick and instead using the keyboard's Enter key (default), I can access the Battle settings from the main menu with that button so I know the mapping is normal.  However when I enter a match, the Start button no longer works!  Training, Challenge, Story... and yet when I restart and return to the main menu, it brings up the battle settings as expected.  It's really really weird.

**Comment by dantarion** [comment]
Maybe you have enabled the "hold start to pause" option?

**Comment by wanderrful** [comment]
So here's what happened:  when I installed the .dll files, I tried to look for where the control button config thing was so that I could test the buttons to make sure they work properly.  The first place I checked was the Settings tab in the main menu because that makes sense, right?  No of course not.  Apparently, while I was scrolling through the settings submenus searching for this mysterious button check menu I must have accidentally switched the pause thing from Type A to Type B without realizing it somehow.

I'll close this thread because I'm a fucking retard.  I had no idea that feature even [i]existed[/i] much less that it was a thing you could do.  Legitimately thought the game disabled some subtle bullshit to deter hackers or whatever.  I was so confused.

**Comment by dantarion** [comment]
Awesome<3
